name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        run: go test -v ./...

      - name: Build for Linux
        run: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o ut2u-linux-amd64 .

      - name: Build for Windows
        run: CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -o ut2u.exe .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ut2u-linux-amd64
            ut2u.exe
